INSERT INTO mst_category (id, category_name, category_description, created_at, updated_at) VALUES (1, '食事パン', '食事用のパン', current_timestamp, current_timestamp);
INSERT INTO mst_category (id, category_name, category_description, created_at, updated_at) VALUES (2, 'おかずパン', '小腹が減った時用', current_timestamp, current_timestamp);
INSERT INTO mst_category (id, category_name, category_description, created_at, updated_at) VALUES (3, '菓子パン', 'おやつに最適', current_timestamp, current_timestamp);
INSERT INTO mst_category (id, category_name, category_description, created_at, updated_at) VALUES (4, '糖質OFF', '痩せたいあなたへ', current_timestamp, current_timestamp);

INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (1, '食パン', 'しょくぱん', 'ふわふわな食感です', 1, 500, '/img/WhiteBread.jpg', '2019/01/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (2, 'クロワッサン', 'くろわっさん', 'サクサクな食感です', 1, 340, '/img/CrescentRoll.jpg', '2019/01/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (3, 'ウインナーロール', 'ういんなーろーる', 'カリカリな食感です', 2, 280, '/img/WienerRoll.jpg', '2019/01/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (4, '焼きそばパン', 'やきそばぱん', '香ばしい香りです', 2, 280, '/img/YakisobaPan.jpg', '2019/01/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (5, 'メロンパン', 'めろんぱん', 'さくふわな食感です', 3, 250, '/img/MelonPan.jpg', '2019/01/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (6, 'あんパン', 'あんぱん', '中にあんこが入ってます', 3, 250, '/img/Anpan.jpg', '2019/01/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (7, 'ベーグル', 'ベーぐる', 'もっちりな食感です', 4, 180, '/img/Bagle.jpg', '2019/01/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (8, 'ロールパン', 'ろーるぱん', '老若男女に人気です', 4, 180, '/img/Roll.jpg', '2019/01/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (9, 'フランスパン', 'ふらんすぱん', '本場の味です', 1, 300, '/img/FrenchBread.jpg', '2019/03/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (10, 'チョコパン', 'ちょこぱん', 'お子様に大人気', 3, 280, '/img/ChololateRoll.jpg', '2019/04/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (11, '揚げパン', 'あげぱん', '懐かしの味', 3, 300, '/img/FriedBun.jpg', '2019/05/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (12, 'クリームパン', 'クリームパン', '甘さ控えめで大人にも大人気', 3, 200, '/img/CreamBread.jpg', '2019/06/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (13, 'レーズンパン', 'れーずんぱん', '小腹が空いた時にピッタリ', 4, 240, '/img/PanAuRasin.jpg', '2019/07/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (14, 'カレーパン', 'かれーぱん', 'ランチにどうぞ', 1, 180, '/img/CurryBun.jpg', '2019/08/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (15, 'ピザトースト', 'ぴざとーすと', '香ばしい香りがたまらない', 1, 350, '/img/PizzaToast.jpg', '2019/09/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (16, 'チーズパン', 'ちーずぱん', 'チーズの味わたっぷり', 1, 190, '/img/CheeseRoll.jpg', '2019/10/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (17, 'サンドイッチ', 'さんどいっち', 'コーヒーと一緒にどうぞ', 1, 240, '/img/Sandwich.jpg', '2019/11/01', 'サンプル株式会社', current_timestamp, current_timestamp);
INSERT INTO mst_product (id, product_name, product_name_kana, product_description, category_id, price, image_full_path, release_date, release_company,  created_at, updated_at) VALUES (18, 'フルーツデニッシュ', 'ふるーつでにっしゅ', '甘いのが好きなあなたへ', 3, 290, '/img/FruitDanish.jpg', '2019/12/01', 'サンプル株式会社', current_timestamp, current_timestamp);

select * from mst_category;
select * from mst_product order by id;
